/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef search_id_CONSTANTS_H
#define search_id_CONSTANTS_H

#include "search_id_types.h"

namespace Thrift_Example {

class search_idConstants {
 public:
  search_idConstants();

};

extern const search_idConstants g_search_id_constants;

} // namespace

#endif
