/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "search_id_constants.h"

namespace Thrift_Example {

const search_idConstants g_search_id_constants;

search_idConstants::search_idConstants() {
}

} // namespace

