/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Search_H
#define Search_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "search_id_types.h"

namespace Thrift_Example {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class SearchIf {
 public:
  virtual ~SearchIf() {}
  virtual void searchName(Response& _return, const int32_t id) = 0;
};

class SearchIfFactory {
 public:
  typedef SearchIf Handler;

  virtual ~SearchIfFactory() {}

  virtual SearchIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SearchIf* /* handler */) = 0;
};

class SearchIfSingletonFactory : virtual public SearchIfFactory {
 public:
  SearchIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<SearchIf>& iface) : iface_(iface) {}
  virtual ~SearchIfSingletonFactory() {}

  virtual SearchIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(SearchIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<SearchIf> iface_;
};

class SearchNull : virtual public SearchIf {
 public:
  virtual ~SearchNull() {}
  void searchName(Response& /* _return */, const int32_t /* id */) {
    return;
  }
};

typedef struct _Search_searchName_args__isset {
  _Search_searchName_args__isset() : id(false) {}
  bool id :1;
} _Search_searchName_args__isset;

class Search_searchName_args {
 public:

  Search_searchName_args(const Search_searchName_args&);
  Search_searchName_args& operator=(const Search_searchName_args&);
  Search_searchName_args() : id(0) {
  }

  virtual ~Search_searchName_args() throw();
  int32_t id;

  _Search_searchName_args__isset __isset;

  void __set_id(const int32_t val);

  bool operator == (const Search_searchName_args & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    return true;
  }
  bool operator != (const Search_searchName_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Search_searchName_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Search_searchName_pargs {
 public:


  virtual ~Search_searchName_pargs() throw();
  const int32_t* id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Search_searchName_result__isset {
  _Search_searchName_result__isset() : success(false) {}
  bool success :1;
} _Search_searchName_result__isset;

class Search_searchName_result {
 public:

  Search_searchName_result(const Search_searchName_result&);
  Search_searchName_result& operator=(const Search_searchName_result&);
  Search_searchName_result() {
  }

  virtual ~Search_searchName_result() throw();
  Response success;

  _Search_searchName_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const Search_searchName_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Search_searchName_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Search_searchName_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Search_searchName_presult__isset {
  _Search_searchName_presult__isset() : success(false) {}
  bool success :1;
} _Search_searchName_presult__isset;

class Search_searchName_presult {
 public:


  virtual ~Search_searchName_presult() throw();
  Response* success;

  _Search_searchName_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class SearchClient : virtual public SearchIf {
 public:
  SearchClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SearchClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void searchName(Response& _return, const int32_t id);
  void send_searchName(const int32_t id);
  void recv_searchName(Response& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SearchProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<SearchIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (SearchProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_searchName(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SearchProcessor(::apache::thrift::stdcxx::shared_ptr<SearchIf> iface) :
    iface_(iface) {
    processMap_["searchName"] = &SearchProcessor::process_searchName;
  }

  virtual ~SearchProcessor() {}
};

class SearchProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  SearchProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< SearchIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< SearchIfFactory > handlerFactory_;
};

class SearchMultiface : virtual public SearchIf {
 public:
  SearchMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<SearchIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SearchMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<SearchIf> > ifaces_;
  SearchMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<SearchIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void searchName(Response& _return, const int32_t id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->searchName(_return, id);
    }
    ifaces_[i]->searchName(_return, id);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class SearchConcurrentClient : virtual public SearchIf {
 public:
  SearchConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SearchConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void searchName(Response& _return, const int32_t id);
  int32_t send_searchName(const int32_t id);
  void recv_searchName(Response& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
